version: "3.9"

services:
  goboxd:
    build:
      context: .
      dockerfile: Dockerfile
      target: nsjail-server
    image: goboxd:latest
    container_name: goboxd
    ports:
      - "8000:8000"
    # Using privileged (nsjail requires SYS_ADMIN)
    privileged: true
    restart: unless-stopped
    environment:
      - CONFIG_PATH=/app/config/languages.yaml
